on: 
  pull_request:
    branches:
      - qa
    types: [closed]
name: Publish QA Main dashboard
jobs:
  web-deploy:
    name: Deploy To QA Main dashboard
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: Build Project
      run: |
        npm install
        cp qa.env .env
        cat .env
        npm run build --if-present
    
    - name: List output files
      run: ls
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        protocol: ftps
        server: ${{ secrets.FTP_QA_SERVER }} 
        username: ${{ secrets.FTP_QA_USERNAME }}
        password: ${{ secrets.FTP_QA_PASSWORD }}
        server-dir: ${{ secrets.FTP_QA_SERVER_DIR }}
